replicaCount: 2

image:
  repository: rasoltani/kaas-api
  tag: dev
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: full-access-account

podAnnotations: {}

resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 0.5
    memory: 256Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: api.kubernetes.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

rbac:
  create: true

fullnameOverride: ""
nameOverride: ""
