apiVersion: apps/v1
kind: Deployment
metadata:
  name: dba-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dba-app
  template:
    metadata:
      labels:
        app: dba-app
    spec:
      containers:
      - name: dba-app
        image: rasoltani/dba-app:dev
        ports:
        - containerPort: 1323
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres_user:password@postgres-master/postgres"
