apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kaas-api
  template:
    metadata:
      labels:
        app: kaas-api
    spec:
      serviceAccountName: full-access-account
      containers:
      - name: kaas-api
        image: rasoltani/kaas-api:dev
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"