apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: {{ .Values.postgres.master.user | b64enc | quote }}
  postgres-password: {{ .Values.postgres.master.password | b64enc | quote }}
  replica-user: {{ .Values.postgres.replica.user | b64enc | quote }}
  replica-password: {{ .Values.postgres.replica.password | b64enc | quote }}
