apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthz-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthz
      monitor: "true"
  template:
    metadata:
      labels:
        app: healthz
        monitor: "true"
    spec:
      containers:
      - name: healthz
        image: rasoltani/healthz:dev
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"