apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kaas-api
  template:
    metadata:
      labels:
        app: kaas-api
    spec:
      serviceAccountName: full-access-account
      containers:
      - name: kaas-api
        image: rasoltani/kaas-api:dev2
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 2
        startupProbe:
          httpGet:
            path: /startup
            port: 8081
          failureThreshold: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"